name: Launch the tests from the back-to-èthe-future module

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: 
      - main 

jobs:
  Python_tests:
    name: Run Python code tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.11

      - name: Run unit tests
        run: |
          python3 -m unittest discover -v
